data_parameters:
  batch_size: 8
  cat_encoding: txt_emb
  scaling_type: null
  serialize: true
exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  device: cuda
  result_path: ./results/hpo
  runs: 5
model_parameters:
  epoch: 5
  model: HuggingFaceTB/SmolLM-135M
  n_permutations: 21
