data_parameters:
  batch_size: 64
  cat_encoding: onehot
  scaling_type: minmax
  serialize: false
exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  device: cuda
  result_path: ./results/hpo
  runs: 5
model_parameters:
  act: ReLU
  bias: false
  hidden_dims: 100,50
  lr: 0.0005
  rep_dim: 32
