data_parameters:
  batch_size: 64
  cat_encoding: int
  scaling_type: minmax
  serialize: false
exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  device: cuda
  result_path: ./results/hpo
  runs: 5
model_parameters:
  bootstrap: false
  contamination: 0.2
  max_features: 1.0
  max_samples: 0.7
  n_estimators: 50
  random_state: 42
