data_parameters:
  batch_size: 64
  cat_encoding: int
  scaling_type: standard
exp:
  best_cfg_path: ./configs/HPO_best
  checkpoint_path: ./checkpoints/hpo
  device: cuda
  result_path: ./results/hpo
  runs: 5
model_parameters:
  contamination: 0.1
  kernel: rbf
  nu: 0.2
