exp:
  runs: 5
  device: cuda
  checkpoint_path: ./checkpoints/default
  result_path: ./results/default

data_parameters:
  serialize: False
  scaling_type: 
  cat_encoding: txt_emb
  batch_size: 64

model_parameters:
  kernel: rbf
  nu: 0.5
  contamination: 0.1