exp:
  device: cuda
  checkpoint_path: ./checkpoints/default
  result_path: ./results/default

data_parameters:
  serialize: True
  scaling_type: 
  cat_encoding: txt_emb
  batch_size: 64

model_parameters:
  epochs: 5
  model: smolLM
  n_permutations: 21
