exp:
  runs: 5
  device: cuda
  checkpoint_path: ./checkpoints/default
  result_path: ./results/default

data_parameters:
  serialize: False
  scaling_type: standard
  cat_encoding: onehot
  batch_size: 64


model_parameters:
  standardization: True
  n_components: 10
  n_selected_components: 5
  contamination: 0.1
  whiten: True
  weighted: True
  svd_solver: auto