exp:
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo

study:
  direction: maximize
  storage: "sqlite:///exp_db/retab.sqlite3"
  n_trials: 1000

data_parameters:
  serialize: False
  batch_size: 1000

model_parameters:
  bias: False

hyperparameters:
  data_parameters:
    scaling_type:
      type: categorical
      grid: [standard, minmax]
    cat_encoding:
      type: categorical
      grid: [int, onehot]
  
  model_parameters:
    lr:
      type: categorical
      grid: [0.001]
    
    act:
      type: categorical
      grid: ["ReLU", "LeakyReLU", "Tanh"]
    
    rep_dim:
      type: categorical
      grid: [64, 128, 256, 512]
    
    hidden_dims:
      type: categorical
      grid: ["100,50", "200,100", "300,150", "128,64", "256,128", "512,256"]
    
    n_ensemble:
      type: categorical
      grid: [20, 50, 100, 200]
    
    n_estimators:
      type: categorical
      grid: [3, 6, 10, 15]
    
    max_samples:
      type: categorical
      grid: [128, 256, 512, 1024]
