exp:
  runs: 5
  device: cuda
  best_cfg_path: ./configs/hpo_best
  checkpoint_path: ./checkpoints/hpo
  result_path: ./results/hpo

study:
  direction: maximize
  storage: "sqlite:///exp_db/retab.sqlite3"
  n_trials: 1000

data_parameters:
  serialize: False
  batch_size: 64

model_parameters:
  bias: False

hyperparameters:
  data_parameters:
    scaling_type: 
      type: categorical
      grid: [standard, minmax]
    cat_encoding:
      type: categorical
      grid: [int, onehot]
      
  model_parameters:  
    lr: 
      type: categorical
      grid: [0.0001, 0.0005, 0.001, 0.005]
    act:
      type: categorical
      grid: ["ReLU", "LeakyReLU", "Tanh"]
    # GOAD 핵심 파라미터들
    n_trans:
      type: categorical
      grid: [128, 256, 512, 1024]
    trans_dim:
      type: categorical
      grid: [16, 32, 64, 128]
    alpha:
      type: categorical
      grid: [0.01, 0.05, 0.1, 0.2, 0.5]
    margin:
      type: categorical
      grid: [0.5, 1.0, 1.5, 2.0]
    hidden_dim:
      type: categorical
      grid: [4, 8, 16, 32]
    n_layers:
      type: categorical
      grid: [3, 5, 7, 9]